export enum Role {
  ADMIN = "ADMIN",
  OPERATIONS_MANAGER = "OPERATIONS_MANAGER",
  MANAGER = "MANAGER",
  TEAM_LEADER = "TEAM_LEADER",
  AFFILIATE = "AFFILIATE",
  PARENT = "PARENT",
  CUSTOMER = "CUSTOMER",
  FINANCE = "FINANCE",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  PENDING = "PENDING"
}

export enum PaymentStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED"
}
