"use server";

import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { Role } from "@/lib/types";

export async function getTeamLeaderStats() {
    const session = await auth();
    const role = (session?.user as any)?.role;
    
    if (!session?.user?.id || role !== "TEAM_LEADER") {
        return null;
    }

    const userId = session.user.id;

    // Get count of team members (affiliates assigned to this team leader)
    const teamCount = await prisma.user.count({
        where: { teamLeaderId: userId, role: "AFFILIATE" }
    });

    // Get team earnings (commissions earned by team members where this user is the team leader)
    // Note: Override commissions for the team leader are already in their personal commission list
    // This stat is to show total volume generated by their team.
    
    // First get team member IDs
    const teamMembers = await prisma.user.findMany({
        where: { teamLeaderId: userId, role: "AFFILIATE" },
        select: { id: true }
    });
    const teamMemberIds = teamMembers.map(m => m.id);

    // Total volume generated by team
    const teamVolume = await prisma.commission.aggregate({
        where: { userId: { in: teamMemberIds } },
        _sum: { amount: true }
    });

    // Count of sales by team
    const teamSalesCount = await prisma.commission.count({
        where: { userId: { in: teamMemberIds } }
    });

    return {
        teamCount,
        teamVolume: Number(teamVolume._sum.amount) || 0,
        teamSalesCount
    };
}

export async function getTeamMembers() {
    const session = await auth();
    const role = (session?.user as any)?.role;
    
    if (!session?.user?.id || role !== "TEAM_LEADER") {
        throw new Error("Unauthorized");
    }

    const teamMembers = await prisma.user.findMany({
        where: { teamLeaderId: session.user.id },
        select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
            status: true,
            createdAt: true,
            profilePictureUrl: true,
            _count: {
                select: {
                    referrals: true,
                    referredOrders: true
                }
            }
        },
        orderBy: { createdAt: "desc" }
    });

    return teamMembers.map(m => ({
        ...m,
        name: `${m.firstName || ""} ${m.lastName || ""}`.trim() || m.email,
        salesCount: m._count.referrals + m._count.referredOrders
    }));
}
